---
- name: Consul Server Kurulumu
  hosts: consul_servers
  become: yes
  tasks:
    - name: HashiCorp Reposunu kurma
      shell: "dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"

    - name: Sadece Consul Paketini Kur
      dnf:
        name: consul
        state: present


    - name: Consul dizinlerini olustur
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: consul
        group: consul
        mode: '0755'
      loop:
        - /var/lib/consul
        - /var/log/consul

    - name: Consul Server conf  templateden bas
      template:
        src: templates/consul_server.json.j2
        dest: /etc/consul.d/consul.json
        owner: consul
        group: consul

    - name: consul_http_token dosyasini olu¿tur ve tokeni yaz
      copy:
        dest: /etc/consul.d/consul_http_token
        content: "{{ consul_master_token }}"
        owner: consul       
        group: consul
        mode: '0600'        


    - name: Consul Servisini Baslat
      systemd: { name: consul, state: restarted, enabled: yes }

- name: Get PostgreSQL Version
  hosts: patroni_nodes
  vars_prompt:
    - name: "version"
      prompt: "Which PostgreSQL version do you want to install? (17 or 15)"
      private: no

  tasks:
  

   - name: Install the PostgreSQL 17 repository RPM
     become: yes
     yum:
       name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
       state: present
       validate_certs: yes
       disable_gpg_check: yes
     when: version == "17"


   - name: HashiCorp Repolarini patroni clustera ekle 
     shell: |
        dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

   - name: PostgreSQL  disble et 
     become: yes
     shell: "dnf -qy --disablerepo='pgdg*' module disable postgresql"

   - name: PostgreSQL Paketlerini Kur
     become: yes
     shell: "dnf install -y postgresql{{version}}-server postgresql{{version}}-contrib --nogpgcheck"
  

   - name: PostgreSQL postgresq python-consul
     shell: |
          
           python3 -m pip install patroni[consul]
           python3 -m pip install python-consul


   - name: Consul Paketini Kur
     shell: "dnf install -y consul --nogpgcheck"
 
   - name: PostgreSQL patroni python-consul
     shell: "python3 -m pip install python-consul"

   - name: Patroni ve Python paketlerini kur 
     shell: "dnf install -y patroni python3-psycopg2 --nogpgcheck"


   - name: Consul Client confu templateden al
     template:
        src: templates/consul_client.json.j2
        dest: /etc/consul.d/consul.json
        owner: consul
        group: consul

   - name: Patroni confu templateden al
     template:
        src: templates/patroni.yml.j2
        dest: /etc/patroni.yml
        owner: postgres
        group: postgres


   - name: Patroni dizinlerinin owner ve permission ayarlari
     ansible.builtin.file:
       path: "{{ item }}"
       state: directory
       owner: postgres
       group: postgres
       mode: '0700'
     loop:
      - /etc/patroni
      - /var/log/patroni

        
   - name: Patroni systemd unit dosyasini templateden al
     template:
      src: patroni.service.j2
      dest: /etc/systemd/system/patroni.service
      owner: root
      group: root
      mode: '0644'

   - name: systemd daemon-reload
     systemd:
       daemon_reload: yes


   - name: Servisleri restart et
     systemd:
            name: "{{ item }}"
            state: restarted
            enabled: yes
            daemon_reload: yes
     loop: [consul, patroni]

- hosts: patroni_nodes
  gather_facts: true
  tasks:
   - name: pgbouncer install
     include_tasks: pg_bouncer.yml
     tags:
        - pgbouncer



